#!/usr/bin/env node
const path = require('path')
const fs = require('fs')

// Path to bundle
const BUNDLE_PATH = path.join(__dirname, '..', 'dist', 'cloop.js')

// Read bundle
const bundle = fs.readFileSync(BUNDLE_PATH, 'utf-8')

// Replace global refs with an isomorphic version
const processed = bundle.replace(
  /([^.])parcelRequire/g,
  '$1(typeof window === \'undefined\' ? global : window).parcelRequire'
)

// Write bundle
fs.writeFileSync(BUNDLE_PATH, processed)
