#!/usr/bin/env node
const path = require('path')
const fs = require('fs')

// Path to bundle
const BUNDLE_PATH = path.join(__dirname, '..', 'dist', 'cloop.js')

// Read bundle
const bundle = fs.readFileSync(BUNDLE_PATH, 'utf-8')

// Replace global refs with an isomorphic version
const isomorphicGlobal = 'var ↂ=(typeof window === \'undefined\' ? global : window);'
const processed = bundle.replace(/parcelRequire/g, 'ↂ.parcelRequire')

// Write bundle
fs.writeFileSync(BUNDLE_PATH, isomorphicGlobal + processed)
