name: CI
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Deps
        run: yarn install
  
      - name: Build
        run: yarn build
  
      - name: Run Bundle Tests
        run: MODULE_DIR=dist yarn test

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  release:
    name: Release
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v1

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      
      - name: Commit dist
        run: git add -f ./dist && git commit -m "Release"
      
      - name: Release
        run: ./tasks/release && git push -f --tags || echo "Done"
