name: CI
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deps
        run: yarn install
  
      - name: Build
        run: yarn build
  
      - name: Run Bundle Tests
        run: MODULE_DIR=dist yarn test

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  release:
    name: Release
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Add git auth
        run: |
          git config --global user.email "release@conlanpatrek.com"
          git config --global user.name "Release Bot"
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      
      - name: Commit dist
        run: git add -f ./dist && git commit -m "Release"
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      
      - name: Tag Release
        run: ./tasks/release
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      
      - name: Push Tags
        run: git push -f --tags
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
