name: CI
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Git Config
        run: |
          git config --global user.name "Release Bot"
          git config --global url."https://${{ secrets.PUBLISH_TOKEN }}@github.com".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.PUBLISH_TOKEN }}@github.com".insteadOf https://github.com

      - uses: actions/checkout@v2

      - name: Install Deps
        run: yarn install
  
      - name: Build
        run: yarn build
  
      - name: Run Bundle Tests
        run: MODULE_DIR=dist yarn test

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  release:
    name: Release
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Git Config
        run: |
          git config --global user.name "Release Bot"
          git config --global url."https://${{ secrets.PUBLISH_TOKEN }}@github.com".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.PUBLISH_TOKEN }}@github.com".insteadOf https://github.com

      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Commit dist
        run: git add -f ./dist && git commit -m "Release"

      - name: Release
        run: yarn release
